### ISSUE TITLE
Error Handling in OWLAPIImpl

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#131]
The module `owl-creator` contains a class `org.archcnl.owlcreator.impl.OWLAPIImpl`. This class is used to build the OWL representation of architecture rules. It is called from the `org.architecture.cnl(.parent)` module, more specifically the class `org.architecture.cnl.generator.ArchcnlGenerator`. This class is only used by `org.architecture.cnl.CNL2OWLGenerator` which is in turn used by the `architecture-description-parser` module. Finally, this module is used by the `toolchain` module, which contains the `main()`.

The class `OWLAPIImpl` contains a few TODOs which indicate places where an appropriate exception handling is missing. All possible exceptions can be considered fatal, i.e. the executions should be aborted (they are caused by file I/O errors). Thus, an error must be propagated in an appropriate way to the `main()` in the `toolchain` module.

The "problem" is that `ArchcnlGenerator` is written in Xtend and **not** in Java. I do not know whether (and if yes, to which extent) exception handling is supported by Xtend. If it is not supported, this restriction could (for instance) be circumvented by adding and setting an "error flag" to the `RuleTypeStorageSingleton` used by `ArchcnlGenerator`, querying this flag in `CNL2OWLGenerator` and throwing a new exception there.

**Comment by Nodmgatall** [comment]
I would look at this.

**Comment by nizap** [comment]
Sounds like a good plan to me. 

To answer your questions: 
- Yes, exceptions are passed upward until they are caught. They should definitely be caught in  toolchain's. execute(), or else ArchCNL crashes because of an uncaught exception. Catching the exception earlier seems inadequate to me, because the execution should be aborted in an orderly fashion, thus the failure must be passed to the highest level anyway. However, the ArchcnlGenerator issue is still important, i.e. you cannot simply pass the exception directly from owl-creator to toolchain (at least as far as I know).
- As long as you use an exception which is of the same type (or a subtype) of one of the exceptions in the catch-blocks, it will be caught. 

Finally, one advice: Instead of passing the error message into newly created exceptions, you can pass the "cause exception" itself/a reference to it. This improves the stack trace of exceptions used by the logging. 

Passing only the message would result in something like this:

```
MyException: Something went wrong
at MyClass.myMethod(MyClass.java.:2)
at CallingClass.callingMethod(CallingClass.java:314)
...
```

Passing the exception which caused the new exception:

```
MyException: Something went wrong
at MyClass.myMethod(MyClass.java.42)
at CallingClass.callingMethod(CallingClass.java.314)
...
Caused By: java.util.IOException: Could not read the file "this-file-is-missing.txt"
at SomeInternalClass.readFile(SomeInternalClass.java:123)
...
```

More details can for instance be found [here](https://www.codejava.net/java-core/exception/understanding-java-exception-chaining-with-code-examples).

**Comment by Nodmgatall** [comment]
enhancement/131-error-handlin-in-owlapiimpl (branch name)
I think I did it.
There were quite some steps that were unexpected.
The function doGenerate overloads a function of an external class/Interface so there I had to use
an UncheckedIOException. Is this something that is acceptable or is there an unwritten rule about this.

Also how do I test this in context of unit tests or our test suit?

**Comment by nizap** [comment]
Looks fine to mine. Imho using an `UncheckedIOException` serves the purpose and it is way better than having no error handling. However, I am no expert of exception handling, so maybe there is a cleaner solution. But again, I think that this suffices. 

Regarding unit testing: You can test the code by using the Mockito and Hamcrest frameworks. Mockito can be used to create a mockup of the generator which throws the desired excpetion when its `doGenerate()` method is called with a few lines of code. Hamcrest offers some handy assertions, such as asserting that an exception is thrown when calling a method. You could use this to mock `generator`in CNL2OWLGenerator and test whether the method ' transformCNLFile' handles this as intended. If you want to avoid introducing new dependencies (if you are not using them already), you could also write your own mockup of the generator manually and write a test like this one:

```java
@Test
void foobar() {
    // given
    // ...

    Throwable thrown = null;
    // when
    try {
         // call transformCNLFile()
    } catch (Throwable t) {
        thrown = t;
    }

    // then
    assertNotNull(e);
    assertTrue(e instanceOf IOException);
    // more assertions
}
```

Imho, unit testing your implementation is out of scope for this issue because it was supposed to be a beginner issue. Nevertheless, I would recommend to write a unit test to ensure that future changes will not break your code. Also, I do not know what the current conventions of your team are, i.e. whether testing is mandatory. From my point of view, you can commit this code and close the issue if you want, maybe creating a separate issue for the tests, but you should resolve this matter with your team.
